[project]
name = "mediaorganizer"
version = "0.1.0"
description = "A Streamlit application for organizing image and video files with metadata extraction"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.48.0",
    "Pillow>=10.0.0",
    "ffmpeg-python>=0.2.0",
]
